export const ActionTypes = {
  FETCH_COCKTAIL_START: 'FETCH_COCKTAIL_START',
  FETCH_COCKTAIL_SUCCESS: 'FETCH_COCKTAIL_SUCCESS',
  FETCH_COCKTAIL_FAIL: 'FETCH_COCKTAIL_FAIL',
  GET_SINGLE_COCKTAIL_START: 'GET_SINGLE_COCKTAIL_START',
  GET_SINGLE_COCKTAIL_SUCCESS: 'GET_SINGLE_COCKTAIL_SUCCESS',
  GET_SINGLE_COCKTAIL_FAIL: 'GET_SINGLE_COCKTAIL_FAIL',
  SEARCH_COCKTAIL_START: 'SEARCH_COCKTAIL_START',
  SEARCH_COCKTAIL_SUCCESS: 'SEARCH_COCKTAIL_SUCCESS',
  SEARCH_COCKTAIL_FAIL: 'SEARCH_COCKTAIL_FAIL',
  FILTER_COCKTAIL_START: 'FILTER_COCKTAIL_START',
  FILTER_COCKTAIL_SUCCESS: 'FILTER_COCKTAIL_SUCCESS',
  FILTER_COCKTAIL_FAIL: 'FILTER_COCKTAIL_FAIL',

  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',

  USER_REGISTER_START: 'USER_REGISTER_START',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

  ADD_FAVORITE_START: 'ADD_FAVORITE_START',
  ADD_FAVORITE_SUCCESS: 'ADD_FAVORITE_SUCCESS',
  ADD_FAVORITE_FAIL: 'ADD_FAVORITE_FAIL',

  REMOVE_FAVORITE_START: 'REMOVE_FAVORITE_START',
  REMOVE_FAVORITE_SUCCESS: 'REMOVE_FAVORITE_SUCCESS',
  REMOVE_FAVORITE_FAIL: 'REMOVE_FAVORITE_FAIL',
};
