export const ActionTypes = {
  FETCH_COCKTAIL_START: 'FETCH_COCKTAIL_START',
  FETCH_COCKTAIL_SUCCESS: 'FETCH_COCKTAIL_SUCCESS',
  FETCH_COCKTAIL_FAIL: 'FETCH_COCKTAIL_FAIL',
  GET_SINGLE_COCKTAIL_START: 'GET_SINGLE_COCKTAIL_START',
  GET_SINGLE_COCKTAIL_SUCCESS: 'GET_SINGLE_COCKTAIL_SUCCESS',
  GET_SINGLE_COCKTAIL_FAIL: 'GET_SINGLE_COCKTAIL_FAIL',
  SEARCH_COCKTAIL_START: 'SEARCH_COCKTAIL_START',
  SEARCH_COCKTAIL_SUCCESS: 'SEARCH_COCKTAIL_SUCCESS',
  SEARCH_COCKTAIL_FAIL: 'SEARCH_COCKTAIL_FAIL',
  FILTER_COCKTAIL_START: 'FILTER_COCKTAIL_START',
  FILTER_COCKTAIL_SUCCESS: 'FILTER_COCKTAIL_SUCCESS',
  FILTER_COCKTAIL_FAIL: 'FILTER_COCKTAIL_FAIL',

  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_OUT: 'SIGN_OUT',

  USER_SIGN_UP: 'USER_SIGN_UP',
  USER_SIGN_UP_FAIL: 'USER_SIGN_UP_FAIL',
};
